{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actually-lite-llm.fullname" . }}-config
  labels:
    {{- include "actually-lite-llm.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    {{- .Values.config.inline | nindent 4 }}
{{- end }}
